 
export const APP = {
  OPEN_CHAT: 'OPEN_CHAT',
  SET_ME: 'SET_ME',
  SET_NAME: 'SET_NAME',
  SET_LIST_USER_ONLINE: 'SET_LIST_USER_ONLINE',
  SEND_TO_FRIEND: 'SEND_TO_FRIEND',
  SEND_FILE: 'SEND_FILE',
  ADD_MESSAGE: 'ADD_MESSAGE',
  GET_LIST_USER_ONLINE: 'GET_LIST_USER_ONLINE'
}
