 
export const APP = {
  SET_PERSON_CHAT_WITH: 'SET_PERSON_CHAT_WITH',
  SET_ME: 'SET_ME',
  SET_LIST_USER_ONLINE: 'SET_LIST_USER_ONLINE',
  SEND_TO_FRIEND: 'SEND_TO_FRIEND',
  ADD_MESSAGE: 'ADD_MESSAGE',
  GET_LIST_USER_ONLINE: 'GET_LIST_USER_ONLINE'
}
